### ISSUE TITLE
Add tooltips to input fields

### ISSUE THREAD

**Issue by ondoheer** [ondoheer/amnh-validation-tool#71]
- [ ] Search location
- [ ] Latitude from / to

The moment I started reading through all of the fields, I felt these were the same ones as in the excel, and that they would be trained by Christine. The ones that might need a further explanation are actually our fields, which are mostly buttons!!!

I would add instructions to the footer *add another*, *download csv* what do you think @ericperrotta

**Comment by ericperrotta** [comment]
Going to hold off on the tooltips until we get feedback on what is hard to understand
